stages:
  - build
  - test
  - deploy

# Cache gems (and other files) in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - public/
    - node_modules/

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --cache-copy-layers
      --cache=true
      --destination $CI_REGISTRY_IMAGE:ci-$CI_COMMIT_SHA

test:
  stage: test
  needs:
    - build
  image: $CI_REGISTRY_IMAGE:ci-$CI_COMMIT_SHA
  coverage: '/\(\d+.\d+\%\) covered/'
  script:
  - cd /app
  - bundle exec rails db:create RAILS_ENV=test
  # - bundle exec rails assets:precompile && rails test
  - rails test
  # - echo -n "$RAILS_ENC" > config/master.key && bundle exec rails test

rubocop:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci-$CI_COMMIT_SHA
  script:
    - bundle exec rubocop
