# Rubocop configuration file
# for references see: https://docs.rubocop.org/rubocop/1.21/index.html

AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

  NewCops: enable

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'test/application_system_test_case.rb'
    - 'test/test_helper.rb'
