# Rubocop configuration file
# for references see: https://docs.rubocop.org/rubocop/1.21/index.html

AllCops:
  Exclude:
    - "coverage/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - !ruby/regexp /old_and_unused\.rb$/

  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  AllowedMethods: ['draw']

Metrics/AbcSize:
  Max: 20
