version: '3'

services:
  web:
    build: .
    image: 'x-empfehl-o-mat:latest'
    container_name: x-empfehl-o-mat-web
    command: sh containersetup.sh
    volumes:
      - .:/app/
    ports:
      - "127.0.0.1:30099:3000"
    env_file:
      - .env.docker
    tty: true
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: x-empfehl-o-mat-db
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
